// export const dummyContactsData = {
//     all: {
//         captanAmerica_at_example_com: {
//             username: 'Captain America',
//             mobile_number: '3001',
//             email: 'captanAmerica@example.com',
//             profile_picture: 'https://picsum.photos/id/237/100/100',
//             last_seen: 'online',
//             location: 'New York',
//             status: 'Available',
//             isSeen: false,
//             unSeenMsgCnt: 7,
//             messages: [
//                 { direction: "received", time: "12:00 AM", message: "Hi, how are you?" },
//                 { direction: "sent", time: "12:00 AM", message: "I'm good, thanks!" },
//                 { direction: "received", time: "12:00 AM", message: "What have you been up to lately?" },
//                 { direction: "sent", time: "12:00 AM", message: "Just working on some projects." },
//                 { direction: "received", time: "12:00 AM", message: "Sounds interesting. Anything exciting?" },
//                 { direction: "sent", time: "12:00 AM", message: "Not really, just the usual stuff." },
//             ]
//         },
//         ironMan_at_example_com: {
//             username: 'Iron Man',
//             mobile_number: '3002',
//             email: 'ironMan@example.com',
//             profile_picture: 'https://picsum.photos/id/238/100/100',
//             last_seen: '10-09-2024',
//             location: 'Malibu',
//             status: 'Away',
//             isSeen: true,
//             unSeenMsgCnt: 2,
//             messages: [
//                 { direction: "received", time: "1:00 PM", message: "Hey there!" },
//                 { direction: "sent", time: "1:05 PM", message: "Hello! What's up?" },
//                 { direction: "received", time: "1:10 PM", message: "Just finished some experiments in the lab." },
//                 { direction: "sent", time: "1:15 PM", message: "That sounds cool! Anything exciting?" },
//                 { direction: "received", time: "1:20 PM", message: "Not really, just the usual superhero stuff." },
//                 { direction: "sent", time: "1:25 PM", message: "Well, you are Iron Man after all!" },
//             ]
//         },
//      @: {
//             username: 'Thor',
//             mobile_number: '3003',
//             email: 'thor@example.com',
//             profile_picture: 'https://picsum.photos/id/239/100/100',
//             last_seen: 'online',
//             location: 'Asgard',
//             status: 'In a battle',
//             isSeen: false,
//             unSeenMsgCnt: 5,
//             messages: [
//                 { direction: "received", time: "3:00 PM", message: "Thor, we need your help!" },
//                 { direction: "sent", time: "3:05 PM", message: "I'm on my way! What's the situation?" },
//                 { direction: "received", time: "3:10 PM", message: "It's a giant monster attacking the city!" },
//                 { direction: "sent", time: "3:15 PM", message: "I'll handle it. Hold tight!" },
//                 { direction: "received", time: "3:20 PM", message: "Thanks, Thor! You're our hero!" },
//             ]
//         },
//         thor2_at_example_com: {
//             username: 'Thor',
//             mobile_number: '3003',
//             email: 'thor2@example.com',
//             profile_picture: 'https://picsum.photos/id/239/100/100',
//             last_seen: 'online',
//             location: 'Asgard',
//             status: 'In a battle',
//             isSeen: false,
//             unSeenMsgCnt: 5,
//             messages: [
//                 { direction: "received", time: "3:00 PM", message: "Thor, we need your help!" },
//                 { direction: "sent", time: "3:05 PM", message: "I'm on my way! What's the situation?" },
//                 { direction: "received", time: "3:10 PM", message: "It's a giant monster attacking the city!" },
//                 { direction: "sent", time: "3:15 PM", message: "I'll handle it. Hold tight!" },
//                 { direction: "received", time: "3:20 PM", message: "Thanks, Thor! You're our hero!" },
//             ]
//         },
//         hulk_at_example_com: {
//             username: 'Hulk',
//             mobile_number: '3004',
//             email: 'hulk@example.com',
//             profile_picture: 'https://picsum.photos/id/240/100/100',
//             last_seen: 'typing...',
//             location: 'Gamma Base',
//             status: 'Smashing',
//             isSeen: true,
//             unSeenMsgCnt: 3,
//             messages: [
//                 { direction: "received", time: "2:00 PM", message: "Hulk, we need you for a mission!" },
//                 { direction: "sent", time: "2:05 PM", message: "Hulk is always ready! What's the mission?" },
//                 { direction: "received", time: "2:10 PM", message: "There's a group of villains causing chaos." },
//                 { direction: "sent", time: "2:15 PM", message: "Hulk will smash them! I'm on my way!" },
//             ]
//         },
//         blackWidow_at_example_com: {
//             username: 'Black Widow',
//             mobile_number: '3005',
//             email: 'blackWidow@example.com',
//             profile_picture: 'https://picsum.photos/id/241/100/100',
//             last_seen: '20-02-2012',
//             location: 'Unknown',
//             status: 'Undercover',
//             isSeen: false,
//             unSeenMsgCnt: 8,
//             messages: [
//                 { direction: "received", time: "4:00 PM", message: "Black Widow, we need information on the enemy." },
//                 { direction: "sent", time: "4:05 PM", message: "I'm on a mission. I'll get the intel you need." },
//                 { direction: "received", time: "4:10 PM", message: "Be careful, Natasha. We're counting on you." },
//                 { direction: "sent", time: "4:15 PM", message: "I always am." },
//             ]
//         },
//         hawkeye_at_example_com: {
//             username: 'Hawkeye',
//             mobile_number: '3006',
//             email: 'hawkeye@example.com',
//             profile_picture: 'https://picsum.photos/id/242/100/100',
//             last_seen: '10-05-2024',
//             location: 'S.H.I.E.L.D. Headquarters',
//             status: 'On a mission',
//             isSeen: true,
//             unSeenMsgCnt: 4,
//             messages: [
//                 { direction: "received", time: "5:00 PM", message: "Hawkeye, we need your precision skills." },
//                 { direction: "sent", time: "5:05 PM", message: "I'm always ready. What's the target?" },
//                 { direction: "received", time: "5:10 PM", message: "There's a threat at the border. We need your strategic mind." },
//                 { direction: "sent", time: "5:15 PM", message: "I'll handle it. I've got a quiver full of arrows ready." },
//             ]
//         },
//         drStrange_at_example_com: {
//             username: 'Doctor Strange',
//             mobile_number: '3007',
//             email: 'drStrange@example.com',
//             profile_picture: 'https://picsum.photos/id/243/100/100',
//             last_seen: '10-04-2024',
//             location: 'Sanctum Sanctorum',
//             status: 'In meditation',
//             isSeen: false,
//             unSeenMsgCnt: 6,
//             messages: [
//                 { direction: "received", time: "6:00 PM", message: "Doctor Strange, we need your mystical help." },
//                 { direction: "sent", time: "6:05 PM", message: "I sense a disturbance. I'll investigate." },
//                 { direction: "received", time: "6:10 PM", message: "Be cautious. The threat is magical in nature." },
//                 { direction: "sent", time: "6:15 PM", message: "I'm prepared. I'll keep you updated." },
//             ]
//         },
//         blackPanther_at_example_com: {
//             username: 'Black Panther',
//             mobile_number: '3008',
//             email: 'blackPanther@example.com',
//             profile_picture: 'https://picsum.photos/id/244/100/100',
//             last_seen: '10-03-2024',
//             location: 'Wakanda',
//             status: 'Protecting the kingdom',
//             isSeen: true,
//             unSeenMsgCnt: 1,
//             messages: [
//                 { direction: "received", time: "7:00 PM", message: "T'Challa, we need your leadership." },
//                 { direction: "sent", time: "7:05 PM", message: "I'm always ready to defend Wakanda. What's the issue?" },
//                 { direction: "received", time: "7:10 PM", message: "There's a threat at the border. We need your strategic mind." },
//                 { direction: "sent", time: "7:15 PM", message: "I'll handle it. Wakanda forever!" },
//             ]
//         },
//         spiderMan_at_example_com: {
//             username: 'Spider-Man',
//             mobile_number: '3009',
//             email: 'spiderMan@example.com',
//             profile_picture: 'https://picsum.photos/id/225/100/100',
//             last_seen: '10-02-2024',
//             location: 'Queens',
//             status: 'Swinging around',
//             isSeen: false,
//             unSeenMsgCnt: 9,
//             messages: [
//                 { direction: "received", time: "8:00 PM", message: "Hey, Spidey! We need your help." },
//                 { direction: "sent", time: "8:05 PM", message: "Sure thing! What's the situation?" },
//                 { direction: "received", time: "8:10 PM", message: "There's a villain causing chaos downtown." },
//                 { direction: "sent", time: "8:15 PM", message: "I'll be there in a web-slinging minute!" },
//             ]
//         },
//         loki_at_example_com: {
//             username: 'Loki',
//             mobile_number: '3010',
//             email: 'loki@example.com',
//             profile_picture: 'https://picsum.photos/id/146/100/100',
//             last_seen: '10-01-2024',
//             location: 'Asgard (allegedly)',
//             status: 'Mischief mode',
//             isSeen: true,
//             unSeenMsgCnt: 3,
//             messages: [
//                 { direction: "received", time: "9:00 PM", message: "Loki, what are you up to now?" },
//                 { direction: "sent", time: "9:05 PM", message: "Just a little mischief. Nothing to worry about." },
//                 { direction: "received", time: "9:10 PM", message: "We've heard that before. What's your game, Loki?" },
//                 { direction: "sent", time: "9:15 PM", message: "Oh, you'll find out soon enough." },
//             ]
//         },
//     },
//     favorites: [ 
//         'captanAmerica_at_example_com',
//         'ironMan_at_example_com',
//       @',
//         'hulk_at_example_com',
//         'blackWidow_at_example_com',
//         'hawkeye_at_example_com',
//         'drStrange_at_example_com',
//         'blackPanther_at_example_com',
//         'spiderMan_at_example_com',
//         'loki_at_example_com',
//         'thor2_at_example_com'
//     ],
//     recents: [  
//         'captanAmerica_at_example_com',
//         'ironMan_at_example_com',
//       @',
//         'hulk_at_example_com',
//         'blackWidow_at_example_com',
//         'hawkeye_at_example_com',
//         'drStrange_at_example_com',
//         'blackPanther_at_example_com',
//         'spiderMan_at_example_com',
//         'loki_at_example_com',
//         'thor2_at_example_com'
//      ]
// }


export const dummyContactsData = {
    all: [
        {
            username: 'Captain America',
            mobile_number: '3001',
            email: 'captanAmerica@example.com',
            profile_picture: 'https://picsum.photos/id/237/100/100',
            last_seen: 'online',
            location: 'New York',
            status: 'Available',
            isSeen: false,
            unSeenMsgCnt: 7,
            messages: [
                { direction: "received", time: "12:00 AM", message: "Hi, how are you?" },
                { direction: "sent", time: "12:00 AM", message: "I'm good, thanks!" },
                { direction: "received", time: "12:00 AM", message: "What have you been up to lately?" },
                { direction: "sent", time: "12:00 AM", message: "Just working on some projects." },
                { direction: "received", time: "12:00 AM", message: "Sounds interesting. Anything exciting?" },
                { direction: "sent", time: "12:00 AM", message: "Not really, just the usual stuff." },
            ]
        },
        {
            username: 'Iron Man',
            mobile_number: '3002',
            email: 'ironMan@example.com',
            profile_picture: 'https://picsum.photos/id/238/100/100',
            last_seen: '10-09-2024',
            location: 'Malibu',
            status: 'Away',
            isSeen: true,
            unSeenMsgCnt: 2,
            messages: [
                { direction: "received", time: "1:00 PM", message: "Hey there!" },
                { direction: "sent", time: "1:05 PM", message: "Hello! What's up?" },
                { direction: "received", time: "1:10 PM", message: "Just finished some experiments in the lab." },
                { direction: "sent", time: "1:15 PM", message: "That sounds cool! Anything exciting?" },
                { direction: "received", time: "1:20 PM", message: "Not really, just the usual superhero stuff." },
                { direction: "sent", time: "1:25 PM", message: "Well, you are Iron Man after all!" },
            ]
        },
        {
            username: 'Thor',
            mobile_number: '3003',
            email: 'thor@example.com',
            profile_picture: 'https://picsum.photos/id/239/100/100',
            last_seen: 'online',
            location: 'Asgard',
            status: 'In a battle',
            isSeen: false,
            unSeenMsgCnt: 5,
            messages: [
                { direction: "received", time: "3:00 PM", message: "Thor, we need your help!" },
                { direction: "sent", time: "3:05 PM", message: "I'm on my way! What's the situation?" },
                { direction: "received", time: "3:10 PM", message: "It's a giant monster attacking the city!" },
                { direction: "sent", time: "3:15 PM", message: "I'll handle it. Hold tight!" },
                { direction: "received", time: "3:20 PM", message: "Thanks, Thor! You're our hero!" },
            ]
        },
        {
            username: 'Thor',
            mobile_number: '3003',
            email: 'thor2@example.com',
            profile_picture: 'https://picsum.photos/id/239/100/100',
            last_seen: 'online',
            location: 'Asgard',
            status: 'In a battle',
            isSeen: false,
            unSeenMsgCnt: 5,
            messages: [
                { direction: "received", time: "3:00 PM", message: "Thor, we need your help!" },
                { direction: "sent", time: "3:05 PM", message: "I'm on my way! What's the situation?" },
                { direction: "received", time: "3:10 PM", message: "It's a giant monster attacking the city!" },
                { direction: "sent", time: "3:15 PM", message: "I'll handle it. Hold tight!" },
                { direction: "received", time: "3:20 PM", message: "Thanks, Thor! You're our hero!" },
            ]
        },
        {
            username: 'Hulk',
            mobile_number: '3004',
            email: 'hulk@example.com',
            profile_picture: 'https://picsum.photos/id/240/100/100',
            last_seen: 'typing...',
            location: 'Gamma Base',
            status: 'Smashing',
            isSeen: true,
            unSeenMsgCnt: 3,
            messages: [
                { direction: "received", time: "2:00 PM", message: "Hulk, we need you for a mission!" },
                { direction: "sent", time: "2:05 PM", message: "Hulk is always ready! What's the mission?" },
                { direction: "received", time: "2:10 PM", message: "There's a group of villains causing chaos." },
                { direction: "sent", time: "2:15 PM", message: "Hulk will smash them! I'm on my way!" },
            ]
        },
        {
            username: 'Black Widow',
            mobile_number: '3005',
            email: 'blackWidow@example.com',
            profile_picture: 'https://picsum.photos/id/241/100/100',
            last_seen: '20-02-2012',
            location: 'Unknown',
            status: 'Undercover',
            isSeen: false,
            unSeenMsgCnt: 8,
            messages: [
                { direction: "received", time: "4:00 PM", message: "Black Widow, we need information on the enemy." },
                { direction: "sent", time: "4:05 PM", message: "I'm on a mission. I'll get the intel you need." },
                { direction: "received", time: "4:10 PM", message: "Be careful, Natasha. We're counting on you." },
                { direction: "sent", time: "4:15 PM", message: "I always am." },
            ]
        },
        {
            username: 'Hawkeye',
            mobile_number: '3006',
            email: 'hawkeye@example.com',
            profile_picture: 'https://picsum.photos/id/242/100/100',
            last_seen: '10-05-2024',
            location: 'S.H.I.E.L.D. Headquarters',
            status: 'On a mission',
            isSeen: true,
            unSeenMsgCnt: 4,
            messages: [
                { direction: "received", time: "5:00 PM", message: "Hawkeye, we need your precision skills." },
                { direction: "sent", time: "5:05 PM", message: "I'm always ready. What's the target?" },
                { direction: "received", time: "5:10 PM", message: "There's a threat at the border. We need your strategic mind." },
                { direction: "sent", time: "5:15 PM", message: "I'll handle it. I've got a quiver full of arrows ready." },
            ]
        },
        {
            username: 'Doctor Strange',
            mobile_number: '3007',
            email: 'drStrange@example.com',
            profile_picture: 'https://picsum.photos/id/243/100/100',
            last_seen: '10-04-2024',
            location: 'Sanctum Sanctorum',
            status: 'In meditation',
            isSeen: false,
            unSeenMsgCnt: 6,
            messages: [
                { direction: "received", time: "6:00 PM", message: "Doctor Strange, we need your mystical help." },
                { direction: "sent", time: "6:05 PM", message: "I sense a disturbance. I'll investigate." },
                { direction: "received", time: "6:10 PM", message: "Be cautious. The threat is magical in nature." },
                { direction: "sent", time: "6:15 PM", message: "I'm prepared. I'll keep you updated." },
            ]
        },
        {
            username: 'Black Panther',
            mobile_number: '3008',
            email: 'blackPanther@example.com',
            profile_picture: 'https://picsum.photos/id/244/100/100',
            last_seen: '10-03-2024',
            location: 'Wakanda',
            status: 'Protecting the kingdom',
            isSeen: true,
            unSeenMsgCnt: 1,
            messages: [
                { direction: "received", time: "7:00 PM", message: "T'Challa, we need your leadership." },
                { direction: "sent", time: "7:05 PM", message: "I'm always ready to defend Wakanda. What's the issue?" },
                { direction: "received", time: "7:10 PM", message: "There's a threat at the border. We need your strategic mind." },
                { direction: "sent", time: "7:15 PM", message: "I'll handle it. Wakanda forever!" },
            ]
        },
        {
            username: 'Spider-Man',
            mobile_number: '3009',
            email: 'spiderMan@example.com',
            profile_picture: 'https://picsum.photos/id/225/100/100',
            last_seen: '10-02-2024',
            location: 'Queens',
            status: 'Swinging around',
            isSeen: false,
            unSeenMsgCnt: 9,
            messages: [
                { direction: "received", time: "8:00 PM", message: "Hey, Spidey! We need your help." },
                { direction: "sent", time: "8:05 PM", message: "Sure thing! What's the situation?" },
                { direction: "received", time: "8:10 PM", message: "There's a villain causing chaos downtown." },
                { direction: "sent", time: "8:15 PM", message: "I'll be there in a web-slinging minute!" },
            ]
        },
        {
            username: 'Loki',
            mobile_number: '3010',
            email: 'loki@example.com',
            profile_picture: 'https://picsum.photos/id/146/100/100',
            last_seen: '10-01-2024',
            location: 'Asgard (allegedly)',
            status: 'Mischief mode',
            isSeen: true,
            unSeenMsgCnt: 3,
            messages: [
                { direction: "received", time: "9:00 PM", message: "Loki, what are you up to now?" },
                { direction: "sent", time: "9:05 PM", message: "Just a little mischief. Nothing to worry about." },
                { direction: "received", time: "9:10 PM", message: "We've heard that before. What's your game, Loki?" },
                { direction: "sent", time: "9:15 PM", message: "Oh, you'll find out soon enough." },
            ]
        },
    ],
    favorites: [ 
        'captanAmerica@example.com',
        'ironMan@example.com',
        'thor@example.com',
        'hulk@example.com',
        'blackWidow@example.com',
        'hawkeye@example.com',
        'drStrange@example.com',
        'blackPanther@example.com',
        'spiderMan@example.com',
        'loki@example.com',
        'thor2@example.com'
    ],
    recents: [  
        'captanAmerica@example.com',
        'ironMan@example.com',
        'thor@example.com',
        'hulk@example.com',
        'blackWidow@example.com',
        'hawkeye@example.com',
        'drStrange@example.com',
        'blackPanther@example.com',
        'spiderMan@example.com',
        'loki@example.com',
        'thor2@example.com'
     ]
}
