


export const dummyContactsData = {
    all: {
        "captanAmerica@example.com":{
            _id: "1a",
            username: 'Captain America',
            mobile_number: '3001',
            email: 'captanAmerica@example.com',
            profile_picture: 'https://picsum.photos/id/237/100/100',
            last_seen: 'online',
            location: 'New York',
            status: 'Available',
            isSeen: false,
            unSeenMsgCnt: 7,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "12:00 AM", message: "Hi, how are you?" },
                { id:'2', status: 'read', from: "user", time: "12:00 AM", message: "I'm good, thanks!" },
                { id:'3', status: 'read', from: "connection", time: "12:00 AM", message: "What have you been up to lately?" },
                { id:'4', status: 'read', from: "user", time: "12:00 AM", message: "Just working on some projects." },
                { id:'5', status: 'read', from: "connection", time: "12:00 AM", message: "Sounds interesting. Anything exciting?" },
                { id:'6', status: 'read', from: "user", time: "12:00 AM", message: "Not really, just the usual stuff." },
            ]
        },
        "ironMan@example.com":{
            _id: "2a",
            username: 'Iron Man',
            mobile_number: '3002',
            email: 'ironMan@example.com',
            profile_picture: 'https://picsum.photos/id/238/100/100',
            last_seen: '10-09-2024',
            location: 'Malibu',
            status: 'Away',
            isSeen: true,
            unSeenMsgCnt: 0,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "1:00 PM", message: "Hey there!" },
                { id:'2', status: 'read', from: "user", time: "1:05 PM", message: "Hello! What's up?" },
                { id:'3', status: 'read', from: "connection", time: "1:10 PM", message: "Just finished some experiments in the lab." },
                { id:'4', status: 'read', from: "user", time: "1:15 PM", message: "That sounds cool! Anything exciting?" },
                { id:'5', status: 'read', from: "connection", time: "1:20 PM", message: "Not really, just the usual superhero stuff." },
                { id:'6', status: 'read', from: "user", time: "1:25 PM", message: "Well, you are Iron Man after all!" },
            ]
        },
        "thor@example.com":{
            _id: "3a",
            username: 'Thor',
            mobile_number: '3003',
            email: 'thor@example.com',
            profile_picture: 'https://picsum.photos/id/239/100/100',
            last_seen: 'online',
            location: 'Asgard',
            status: 'In a battle',
            isSeen: false,
            unSeenMsgCnt: 5,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "3:00 PM", message: "Thor, we need your help!" },
                { id:'2', status: 'read', from: "user", time: "3:05 PM", message: "I'm on my way! What's the situation?" },
                { id:'3', status: 'read', from: "connection", time: "3:10 PM", message: "It's a giant monster attacking the city!" },
                { id:'4', status: 'read', from: "user", time: "3:15 PM", message: "I'll handle it. Hold tight!" },
                { id:'5', status: 'read', from: "connection", time: "3:20 PM", message: "Thanks, Thor! You're our hero!" },
            ]
        },
        "thor2@example.com":{
            _id: "4a",
            username: 'Thor',
            mobile_number: '3003',
            email: 'thor2@example.com',
            profile_picture: 'https://picsum.photos/id/239/100/100',
            last_seen: 'online',
            location: 'Asgard',
            status: 'In a battle',
            isSeen: false,
            unSeenMsgCnt: 5,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "3:00 PM", message: "Thor, we need your help!" },
                { id:'2', status: 'read', from: "user", time: "3:05 PM", message: "I'm on my way! What's the situation?" },
                { id:'3', status: 'read', from: "connection", time: "3:10 PM", message: "It's a giant monster attacking the city!" },
                { id:'4', status: 'read', from: "user", time: "3:15 PM", message: "I'll handle it. Hold tight!" },
                { id:'5', status: 'read', from: "connection", time: "3:20 PM", message: "Thanks, Thor! You're our hero!" },
            ]
        },
        "hulk@example.com":{
            _id: "5a",
            username: 'Hulk',
            mobile_number: '3004',
            email: 'hulk@example.com',
            profile_picture: 'https://picsum.photos/id/240/100/100',
            last_seen: 'typing...',
            location: 'Gamma Base',
            status: 'Smashing',
            isSeen: false,
            unSeenMsgCnt: 3,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "2:00 PM", message: "Hulk, we need you for a mission!" },
                { id:'2', status: 'read', from: "user", time: "2:05 PM", message: "Hulk is always ready! What's the mission?" },
                { id:'3', status: 'read', from: "connection", time: "2:10 PM", message: "There's a group of villains causing chaos." },
                { id:'4', status: 'read', from: "user", time: "2:15 PM", message: "Hulk will smash them! I'm on my way!" },
            ]
        },
        "blackWidow@example.com":{
            _id: "6a",
            username: 'Black Widow',
            mobile_number: '3005',
            email: 'blackWidow@example.com',
            profile_picture: 'https://picsum.photos/id/241/100/100',
            last_seen: '20-02-2012',
            location: 'Unknown',
            status: 'Undercover',
            isSeen: true,
            unSeenMsgCnt: 0,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "4:00 PM", message: "Black Widow, we need information on the enemy." },
                { id:'2', status: 'read', from: "user", time: "4:05 PM", message: "I'm on a mission. I'll get the intel you need." },
                { id:'3', status: 'read', from: "connection", time: "4:10 PM", message: "Be careful, Natasha. We're counting on you." },
                { id:'4', status: 'read', from: "user", time: "4:15 PM", message: "I always am." },
            ]
        },
        "hawkeye@example.com":{
            _id: "7a",
            username: 'Hawkeye',
            mobile_number: '3006',
            email: 'hawkeye@example.com',
            profile_picture: 'https://picsum.photos/id/242/100/100',
            last_seen: '10-05-2024',
            location: 'S.H.I.E.L.D. Headquarters',
            status: 'On a mission',
            isSeen: true,
            unSeenMsgCnt: 0,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "5:00 PM", message: "Hawkeye, we need your precision skills." },
                { id:'2', status: 'read', from: "user", time: "5:05 PM", message: "I'm always ready. What's the target?" },
                { id:'3', status: 'read', from: "connection", time: "5:10 PM", message: "There's a threat at the border. We need your strategic mind." },
                { id:'4', status: 'read', from: "user", time: "5:15 PM", message: "I'll handle it. I've got a quiver full of arrows ready." },
            ]
        },
        "drStrange@example.com":{
            _id: "8a",
            username: 'Doctor Strange',
            mobile_number: '3007',
            email: 'drStrange@example.com',
            profile_picture: 'https://picsum.photos/id/243/100/100',
            last_seen: '10-04-2024',
            location: 'Sanctum Sanctorum',
            status: 'In meditation',
            isSeen: false,
            unSeenMsgCnt: 6,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "6:00 PM", message: "Doctor Strange, we need your mystical help." },
                { id:'2', status: 'read', from: "user", time: "6:05 PM", message: "I sense a disturbance. I'll investigate." },
                { id:'3', status: 'read', from: "connection", time: "6:10 PM", message: "Be cautious. The threat is magical in nature." },
                { id:'4', status: 'read', from: "user", time: "6:15 PM", message: "I'm prepared. I'll keep you updated." },
            ]
        },
        "blackPanther@example.com":{
            _id: "9a",
            username: 'Black Panther',
            mobile_number: '3008',
            email: 'blackPanther@example.com',
            profile_picture: 'https://picsum.photos/id/244/100/100',
            last_seen: '10-03-2024',
            location: 'Wakanda',
            status: 'Protecting the kingdom',
            isSeen: false,
            unSeenMsgCnt: 1,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "7:00 PM", message: "T'Challa, we need your leadership." },
                { id:'2', status: 'read', from: "user", time: "7:05 PM", message: "I'm always ready to defend Wakanda. What's the issue?" },
                { id:'3', status: 'read', from: "connection", time: "7:10 PM", message: "There's a threat at the border. We need your strategic mind." },
                { id:'4', status: 'read', from: "user", time: "7:15 PM", message: "I'll handle it. Wakanda forever!" },
            ]
        },
        "spiderMan@example.com":{
            _id: "10a",
            username: 'Spider-Man',
            mobile_number: '3009',
            email: 'spiderMan@example.com',
            profile_picture: 'https://picsum.photos/id/225/100/100',
            last_seen: '10-02-2024',
            location: 'Queens',
            status: 'Swinging around',
            isSeen: true,
            unSeenMsgCnt: 0,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "8:00 PM", message: "Hey, Spidey! We need your help." },
                { id:'2', status: 'read', from: "user", time: "8:05 PM", message: "Sure thing! What's the situation?" },
                { id:'3', status: 'read', from: "connection", time: "8:10 PM", message: "There's a villain causing chaos downtown." },
                { id:'4', status: 'read', from: "user", time: "8:15 PM", message: "I'll be there in a web-slinging minute!" },
            ]
        },
        "loki@example.com":{
            _id: "11a",
            username: 'Loki',
            mobile_number: '3010',
            email: 'loki@example.com',
            profile_picture: 'https://picsum.photos/id/146/100/100',
            last_seen: '10-01-2024',
            location: 'Asgard (allegedly)',
            status: 'Mischief mode',
            isSeen: false,
            unSeenMsgCnt: 3,
            messages: [
                { id:'1', status: 'read', from: "connection", time: "9:00 PM", message: "Loki, what are you up to now?" },
                { id:'2', status: 'read', from: "user", time: "9:05 PM", message: "Just a little mischief. Nothing to worry about." },
                { id:'3', status: 'read', from: "connection", time: "9:10 PM", message: "We've heard that before. What's your game, Loki?" },
                { id:'4', status: 'read', from: "user", time: "9:15 PM", message: "Oh, you'll find out soon enough." },
            ]
        },
    },
    favorites: ["captanAmerica@example.com", "ironMan@example.com", "thor@example.com", "thor2@example.com", "hulk@example.com", "blackWidow@example.com", "hawkeye@example.com", "drStrange@example.com", "blackPanther@example.com", "spiderMan@example.com", "loki@example.com"],
    recents: ["captanAmerica@example.com", "ironMan@example.com", "thor@example.com", "thor2@example.com", "hulk@example.com", "blackWidow@example.com", "hawkeye@example.com", "drStrange@example.com", "blackPanther@example.com", "spiderMan@example.com", "loki@example.com"]

}
