

export const icons = {
  audioFile: "ph:file-audio-bold",
  addContact: "ri:user-add-line",
  addMore: "ri:add-line",
  audioCall: "ri-phone-line",
  back: "ri-arrow-left-line",
  block: "ri:forbid-line",
  cancel: "gridicons:cross",
  chats: "ri:message-3-line",
  connections: "ri:contacts-line",
  darkMode: "ri:moon-line",
  delete: "ri:delete-bin-line",
  edit: "uil:edit",
  editPicture: "clarity:edit-solid",
  email: "ri:mail-line",
  emoji: "ri:emotion-happy-line",
  expend: "iconamoon:arrow-up-2",
  groups: "ri:group-line",
  imageFile: "ph:file-image-bold",
  language: "ri:global-line",
  lightMode: "ri:sun-line",
  logout: "ri-logout-circle-r-line",
  menu: "ri-more-2-fill",
  password: "ri:lock-2-line",
  profile: "ri:user-2-line",
  save: "lucide:check-square",
  search: "ri-search-line",
  messageSender: "ic:sharp-send",
  messageError: "ri:error-warning-line",
  messageSending: "eos-icons:three-dots-loading",
  messageSent: "ri:check-fill",
  messageDelivered: "ri:check-double-fill",
  messageSeen: "ri:check-double-fill",
  messageResend: "ic:baseline-refresh",
  sendMore: "ri-attachment-line",
  settings: "ri:settings-2-line",
  share: "ri:share-line",
  username: "ri:user-2-line",
  vidoeCall: "ri-vidicon-line",
  vidoeFile: "ph:file-video-bold"
};
